### ISSUE TITLE
Add ftp support for go-storage

### ISSUE THREAD

**Issue by Prnyself** [beyondstorage/go-service-ftp#3]
## Description

FTP is the oldest network tool in the history of the Internet and is still widely used in many areas. 
This project will implement [go-storage]'s Storager interface for FTP, 
enabling users to use a unified interface to manipulate data on FTP servers.

## Roadmap

- [x] Choose a well maintained FTP library
- [x] Implement all interface that Storager required
- [x] Setup integration tests
- [x] Add docs in [site](https://github.com/aos-dev/site)
- [x] Add examples in [example](https://github.com/aos-dev/go-storage-example)

[go-storage]: https://github.com/aos-dev/go-storage

**Comment by Xuanwo** [comment]
@npofsi is responsible for this issue.

**Comment by Prnyself** [comment]
`Storager` implemented in #13

**Comment by Prnyself** [comment]
docs added in https://github.com/beyondstorage/site/pull/176

**Comment by Prnyself** [comment]
Integration tests implemented in #16

**Comment by Xuanwo** [comment]
Maybe we can bump a 0.1.0 version?

**Comment by npofsi** [comment]
> Maybe we can bump a 0.1.0 version?

Wait me for a small fix, I find I forgot to fix a bug when I separate last PRs

**Comment by Prnyself** [comment]
[here](https://beyondstorage.io/docs/go-storage/internal/bump-version) is the doc for bumping version, please take this as a reference.

**Comment by Prnyself** [comment]
Example added in https://github.com/beyondstorage/go-storage-example/pull/16

**Comment by Prnyself** [comment]
All five tasks were done, great job! @npofsi
